Add code of conduct & link to Kinvolk's Contribution
kinvolk/headlamp pull request #100
Opened 2020-10-23 10:44 UTC by joaquimrocha

2020-10-23 15:53 UTC, vbatts requested changes

2020-10-23 15:53 UTC, vbatts commented on docs/contributing.md
> +[contribution guidelines on git](https://github.com/kinvolk/contribution/tree/master/git).
same https://github.com/kinvolk/dev-utils/pull/6#discussion_r510979794

2020-10-28 15:23 UTC, joaquimrocha commented
Updated.

2020-10-28 17:16 UTC, vbatts commented
LGTM

2020-10-28 17:16 UTC, merged