Add "make docs" with typedoc and storybook
kinvolk/headlamp pull request #204
Opened 2021-02-23 23:01 UTC by illume

We add api-reference and storybook under docs/development.

Using typedoc for the api-reference.

# How to use

`make docs`

# Testing done

`make docs` outputs static html, and you can view that in the following folders:

- docs/development/storybook
- docs/development/api-reference

2021-02-24 13:39 UTC, joaquimrocha reviewed
The API docs should ideally be generated in markdown, maybe this helps: https://www.npmjs.com/package/typedoc-plugin-markdown

Also commented on the kinvolk/docs repo.

2021-02-24 13:39 UTC, joaquimrocha commented on .gitignore
> +docs/development/api-reference/
Let's call this simply `docs/development/api`.

2021-02-25 12:12 UTC, joaquimrocha requested changes
We still need some work in the integration:

![Screenshot from 2021-02-25 12-10-20](https://user-images.githubusercontent.com/1029635/109151775-819d4480-7762-11eb-94da-c61e64f7c83d.png)

We need to lose the breadcrumb is generates and add the front-matter to the doc files:
```
---
title: THIS TITLE NEEDS TO BE ADDED
---
```

2021-02-25 12:30 UTC, illume commented
Indeed. I have a discussion with the typedoc-plugin-markdown author on how best to proceed generating the front-matter. Will come back to this PR when that discussion is finished.

2021-02-25 14:36 UTC, joaquimrocha commented
> Indeed. I have a discussion with the typedoc-plugin-markdown author on how best to proceed generating the front-matter. Will come back to this PR when that discussion is finished.

Great! Thanks.

BTW, regarding Storybook, I am still a bit reluctant that it'll slow down the website build, so let's keep it out and just add insttructions in the docs on how to run it.
I guess running it locally also makes sense if you're looking into how to develop things anyway.

2021-03-02 12:07 UTC, illume commented
There's a fancy new theme for Hugo now thanks to the typedoc-plugin-markdown author which adds front-matter. This branch now uses the first release of the theme. It still has some rough edges with links in the side bar and slugs, which I'll debug.

2021-03-04 12:54 UTC, illume commented
This now:
- does not build storybook with `make docs`
- looks good in the website
- uses the new hugo theme for the typedoc markdown, with some small fixes to the output until/if that plugin is improved at some point in the future.

The broken test is because of an unrelated issue, see temp hotfix in PR: https://github.com/kinvolk/headlamp/pull/211

2021-03-09 13:34 UTC, illume commented
There's a new typedoc-hugo plugin for typedoc markdown that fixes the remaining issues, and I removed the tidy-up script.

2021-03-16 09:37 UTC, joaquimrocha commented
I have added an extra option to the typedoc's config that hides the TOC on pages (since we already have one being generated by default).

2021-03-16 09:47 UTC, merged