Add clusters dynamically
kinvolk/headlamp pull request #497
Opened 2022-04-22 21:17 UTC by joaquimrocha

WIP still

2022-04-28 12:49 UTC, joaquimrocha commented
CI is failing because of the unreleased new function in the Headlamp class (for plugins).

2022-05-12 16:29 UTC, illume commented
Looks like there's a problem with the types somehow.
```
Error: src/index.tsx(9,18): error TS2339: Property 'setCluster' does not exist on type 'typeof Headlamp'.
make: *** [Makefile:76: plugins-test] Error 2
```

2022-05-12 16:59 UTC, illume requested changes
Looks good to me. There's the type error in CI that needs to be fixed though.

I left some other comments of things that could be improved, but I don't think any of them should block this being merged.

2022-05-12 16:59 UTC, illume commented on frontend/src/lib/k8s/apiProxy.ts
> +export interface ClusterRequest {
It would be good if these had tsdoc strings to explain what they are for.

2022-05-12 16:59 UTC, illume commented on plugins/examples/dynamic-clusters/package.json
> +  "description": "Your Headlamp plugin",
The plugin description should go here.

2022-05-12 16:59 UTC, illume commented on plugins/examples/dynamic-clusters/src/index.tsx
> +          // We should find a better way to make sure the clusters info is reloaded.
I think window.location.reload is good enough, so probably the comment can be removed?

2022-05-12 16:59 UTC, illume commented on plugins/examples/dynamic-clusters/src/index.tsx
> +        });
I'm not sure if we need to show how errors are handled here. This could be added later to this PR.

2022-05-12 21:34 UTC, illume approved these changes
🎈🎉 thanks

2022-05-12 21:45 UTC, merged