Fix `make image`
kinvolk/headlamp pull request #67
Opened 2020-09-25 12:39 UTC by johananl

This PR makes `make image` work. I'm not sure if the produced image works but at least we get an image.
It also adds `node_modules` to `.dockerignore` since this directory is huge and there is no need to send it to the Docker daemon when building images.

2020-09-25 15:25 UTC, joaquimrocha requested changes
I think Ashu had pointed it out but I am not sure what happened after that.
I use podman and it doesn't complain, maybe that;s why I never noticed it.

Anyway, good catch. I'd like only to ask for a slightly less generic title. Something along the lines of:
`Makefile: Add missing dir to image target's docker command`

(With generic titles things take longer to figure out later when we're scrolling through lists of similar messages)

2020-09-25 15:40 UTC, ashu8912 commented
fixes #31

2020-09-25 17:14 UTC, johananl commented
> I think Ashu had pointed it out but I am not sure what happened after that.
> I use podman and it doesn't complain, maybe that;s why I never noticed it.
> 
> Anyway, good catch. I'd like only to ask for a slightly less generic title. Something along the lines of:
> `Makefile: Add missing dir to image target's docker command`
> 
> (With generic titles things take longer to figure out later when we're scrolling through lists of similar messages)

I tried to encompass both of the commits without being too elaborate. Hope it's better now.

2020-09-28 10:59 UTC, joaquimrocha commented
> > I think Ashu had pointed it out but I am not sure what happened after that.
> > I use podman and it doesn't complain, maybe that;s why I never noticed it.
> > Anyway, good catch. I'd like only to ask for a slightly less generic title. Something along the lines of:
> > `Makefile: Add missing dir to image target's docker command`
> > (With generic titles things take longer to figure out later when we're scrolling through lists of similar messages)
> 
> I tried to encompass both of the commits without being too elaborate. Hope it's better now.

I actually meant the commit's title, not the PR one. Sorry if it was not clear.

2020-09-28 11:25 UTC, johananl commented
@joaquimrocha Fixed.

2020-09-28 11:47 UTC, merged