Add Link to reference objects from Role/ClusterRole details view
kinvolk/headlamp pull request #705
Opened 2022-09-16 07:06 UTC by yolossn

Fixes: https://github.com/kinvolk/headlamp/issues/663

2022-09-21 19:31 UTC, joaquimrocha requested changes
Looks good. Left small comments.

2022-09-22 08:51 UTC, yolossn commented on frontend/src/components/role/BindingDetails.tsx
> +                      </Link>
The item here doesn't implement the `KubeObjectInterface` so I think we won't be able to use `ResourceLink` here.

https://github.com/kinvolk/headlamp/blob/main/frontend/src/components/common/Resource/Resource.tsx#L54

2022-09-23 08:09 UTC, ashu8912 approved these changes
LGTM

2022-09-26 17:12 UTC, joaquimrocha commented
I've tested this on a cluster where in one case, a RoleBinding subjects do not have a namespace set to them, and these changes have an error in such case and they expect a namespace to exist.

So I added a fixup commit to avoid that.

2022-09-27 15:25 UTC, merged