Setup releases and update mechanism for desktop app
kinvolk/headlamp pull request #88
Opened 2020-10-12 11:07 UTC by ashu8912

2020-10-12 14:04 UTC, joaquimrocha requested changes

2020-10-12 14:04 UTC, joaquimrocha commented on app/electron/main.js
> +  log.info(text);
Please add a context message here unless the log does it automatically:
```
log.info(`Sending status to window: ${text}`);
```

2020-10-12 14:04 UTC, joaquimrocha commented on app/electron/main.js
> +  sendStatusToWindow('Update not available.');
You're using a period here, but not in the other messages. Please remove it from here.

2020-10-12 14:04 UTC, joaquimrocha commented on app/electron/main.js
> +
The `package-lock.json` change belongs to the previous patch.

2020-10-12 16:46 UTC, ashu8912 commented on app/package.json
> +    "package": "mkdir -p build && cp -r ../frontend/build/* ./build && electron-builder build --linux -c.extraMetadata.main=build/electron/main.js --publish never",
true, its default to what system we are building it

2020-10-13 10:23 UTC, joaquimrocha approved these changes

2020-10-13 10:23 UTC, merged